In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
# df["cast"] = df["cast"].replace(np.nan, 0)
#arr = df.iloc[1, df["cast"]].split(", ")
#arr


# df['no_of_cast'] = df.cast.apply(lambda x: len(str(x).split(' ')))
# df.head(5)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [4]:
df.groupby("type")["country"].value_counts()

type     country
Movie    United States                               2058
         India                                        893
         United Kingdom                               206
         Canada                                       122
         Spain                                         97
                                                     ...
TV Show  United States, Russia                          1
         United States, Singapore                       1
         United States, Sweden                          1
         United States, United Kingdom, Australia       1
         Uruguay, Germany                               1
Name: country, Length: 847, dtype: int64

In [5]:
data = df.groupby(["type", "rating", "no_of_cast"])['country'].value_counts()
data.head(5)

KeyError: 'no_of_cast'

In [6]:
df.groupby('type')['rating'].value_counts()

type     rating
Movie    TV-MA       2062
         TV-14       1427
         R            797
         TV-PG        540
         PG-13        490
         PG           287
         TV-Y7        139
         TV-Y         131
         TV-G         126
         NR            75
         G             41
         TV-Y7-FV       5
         NC-17          3
         UR             3
         66 min         1
         74 min         1
         84 min         1
TV Show  TV-MA       1145
         TV-14        733
         TV-PG        323
         TV-Y7        195
         TV-Y         176
         TV-G          94
         NR             5
         R              2
         TV-Y7-FV       1
Name: rating, dtype: int64

In [9]:
df.groupby(["type", "listed_in"]).count().head(20)

                                                          show_id  title  \
type  listed_in
Movie Action & Adventure                                      128    128
      Action & Adventure, Anime Features                        1      1
      Action & Adventure, Anime Features, Children & ...        4      4
      Action & Adventure, Anime Features, Classic Movies        2      2
      Action & Adventure, Anime Features, Horror Movies         1      1
      Action & Adventure, Anime Features, Internation...       38     38
      Action & Adventure, Anime Features, Sci-Fi & Fa...        4      4
      Action & Adventure, Children & Family Movies              2      2
      Action & Adventure, Children & Family Movies, C...        4      4
      Action & Adventure, Children & Family Movies, C...        5      5
      Action & Adventure, Children & Family Movies, C...        1      1
      Action & Adventure, Children & Family Movies, D...        3      3
      Action & Adventure, Children & Family Movies, I...        1      1
      Action & Adventure, Children & Family Movies, S...        6      6
      Action & Adventure, Classic Movies                        5      5
      Action & Adventure, Classic Movies, Comedies              4      4
      Action & Adventure, Classic Movies, Cult Movies           5      5
      Action & Adventure, Classic Movies, Dramas                9      9
      Action & Adventure, Classic Movies, Internation...        1      1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...        1      1

                                                          director  cast  \
type  listed_in
Movie Action & Adventure                                       128   128
      Action & Adventure, Anime Features                         1     1
      Action & Adventure, Anime Features, Children & ...         4     4
      Action & Adventure, Anime Features, Classic Movies         2     2
      Action & Adventure, Anime Features, Horror Movies          1     1
      Action & Adventure, Anime Features, Internation...        38    37
      Action & Adventure, Anime Features, Sci-Fi & Fa...         4     4
      Action & Adventure, Children & Family Movies               1     1
      Action & Adventure, Children & Family Movies, C...         4     4
      Action & Adventure, Children & Family Movies, C...         5     5
      Action & Adventure, Children & Family Movies, C...         1     1
      Action & Adventure, Children & Family Movies, D...         3     3
      Action & Adventure, Children & Family Movies, I...         1     1
      Action & Adventure, Children & Family Movies, S...         6     6
      Action & Adventure, Classic Movies                         5     5
      Action & Adventure, Classic Movies, Comedies               4     4
      Action & Adventure, Classic Movies, Cult Movies            5     5
      Action & Adventure, Classic Movies, Dramas                 9     9
      Action & Adventure, Classic Movies, Internation...         1     1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...         1     1

                                                          country  date_added  \
type  listed_in
Movie Action & Adventure                                      127         128
      Action & Adventure, Anime Features                        0           1
      Action & Adventure, Anime Features, Children & ...        4           4
      Action & Adventure, Anime Features, Classic Movies        1           2
      Action & Adventure, Anime Features, Horror Movies         1           1
      Action & Adventure, Anime Features, Internation...       34          38
      Action & Adventure, Anime Features, Sci-Fi & Fa...        4           4
      Action & Adventure, Children & Family Movies              2           2
      Action & Adventure, Children & Family Movies, C...        4           4
      Action & Adventure, Children & Family Movies, C...        5           5
      Action & Adventure, Children & Family Movies, C...        1           1
      Action & Adventure, Children & Family Movies, D...        3           3
      Action & Adventure, Children & Family Movies, I...        1           1
      Action & Adventure, Children & Family Movies, S...        6           6
      Action & Adventure, Classic Movies                        5           5
      Action & Adventure, Classic Movies, Comedies              4           4
      Action & Adventure, Classic Movies, Cult Movies           5           5
      Action & Adventure, Classic Movies, Dramas                9           9
      Action & Adventure, Classic Movies, Internation...        1           1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...        1           1

                                                          release_year  \
type  listed_in
Movie Action & Adventure                                           128
      Action & Adventure, Anime Features                             1
      Action & Adventure, Anime Features, Children & ...             4
      Action & Adventure, Anime Features, Classic Movies             2
      Action & Adventure, Anime Features, Horror Movies              1
      Action & Adventure, Anime Features, Internation...            38
      Action & Adventure, Anime Features, Sci-Fi & Fa...             4
      Action & Adventure, Children & Family Movies                   2
      Action & Adventure, Children & Family Movies, C...             4
      Action & Adventure, Children & Family Movies, C...             5
      Action & Adventure, Children & Family Movies, C...             1
      Action & Adventure, Children & Family Movies, D...             3
      Action & Adventure, Children & Family Movies, I...             1
      Action & Adventure, Children & Family Movies, S...             6
      Action & Adventure, Classic Movies                             5
      Action & Adventure, Classic Movies, Comedies                   4
      Action & Adventure, Classic Movies, Cult Movies                5
      Action & Adventure, Classic Movies, Dramas                     9
      Action & Adventure, Classic Movies, Internation...             1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...             1

                                                          rating  duration  \
type  listed_in
Movie Action & Adventure                                     128       128
      Action & Adventure, Anime Features                       1         1
      Action & Adventure, Anime Features, Children & ...       4         4
      Action & Adventure, Anime Features, Classic Movies       2         2
      Action & Adventure, Anime Features, Horror Movies        1         1
      Action & Adventure, Anime Features, Internation...      38        38
      Action & Adventure, Anime Features, Sci-Fi & Fa...       4         4
      Action & Adventure, Children & Family Movies             2         2
      Action & Adventure, Children & Family Movies, C...       4         4
      Action & Adventure, Children & Family Movies, C...       5         5
      Action & Adventure, Children & Family Movies, C...       1         1
      Action & Adventure, Children & Family Movies, D...       3         3
      Action & Adventure, Children & Family Movies, I...       1         1
      Action & Adventure, Children & Family Movies, S...       6         6
      Action & Adventure, Classic Movies                       5         5
      Action & Adventure, Classic Movies, Comedies             4         4
      Action & Adventure, Classic Movies, Cult Movies          5         5
      Action & Adventure, Classic Movies, Dramas               9         9
      Action & Adventure, Classic Movies, Internation...       1         1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...       1         1

                                                          description
type  listed_in
Movie Action & Adventure                                          128
      Action & Adventure, Anime Features                            1
      Action & Adventure, Anime Features, Children & ...            4
      Action & Adventure, Anime Features, Classic Movies            2
      Action & Adventure, Anime Features, Horror Movies             1
      Action & Adventure, Anime Features, Internation...           38
      Action & Adventure, Anime Features, Sci-Fi & Fa...            4
      Action & Adventure, Children & Family Movies                  2
      Action & Adventure, Children & Family Movies, C...            4
      Action & Adventure, Children & Family Movies, C...            5
      Action & Adventure, Children & Family Movies, C...            1
      Action & Adventure, Children & Family Movies, D...            3
      Action & Adventure, Children & Family Movies, I...            1
      Action & Adventure, Children & Family Movies, S...            6
      Action & Adventure, Classic Movies                            5
      Action & Adventure, Classic Movies, Comedies                  4
      Action & Adventure, Classic Movies, Cult Movies               5
      Action & Adventure, Classic Movies, Dramas                    9
      Action & Adventure, Classic Movies, Internation...            1
      Action & Adventure, Classic Movies, Sci-Fi & Fa...            1